name = "blackbox-demo"
main = "./src/index.ts"
compatibility_date = "2026-04-27"

[[routes]]
pattern = "demo.blackboxd.dev/*"
zone_name = "blackboxd.dev"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"
